/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientWalletRouteImport } from './routes/client.wallet'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as WorkerWalletRouteImport } from './routes/worker.wallet'
import { Route as ClientJobsIndexRouteImport } from './routes/client.jobs.index'
import { Route as ClientJobsJobIdRouteImport } from './routes/client.jobs.$jobId'
import { Route as ClientJobsNewRouteImport } from './routes/client.jobs.new'
import { Route as ClientReviewJobIdRouteImport } from './routes/client.review.$jobId'
import { Route as WorkerJobJobIdRouteImport } from './routes/worker.job.$jobId'
import { Route as WorkerTaskJobIdRouteImport } from './routes/worker.task.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientWalletRoute = ClientWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ClientRoute,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerWalletRoute = WorkerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => WorkerRoute,
} as any)
const ClientJobsIndexRoute = ClientJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientJobsJobIdRoute = ClientJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientJobsNewRoute = ClientJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => ClientRoute,
} as any)
const ClientReviewJobIdRoute = ClientReviewJobIdRouteImport.update({
  id: '/review/$jobId',
  path: '/review/$jobId',
  getParentRoute: () => ClientRoute,
} as any)
const WorkerJobJobIdRoute = WorkerJobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerTaskJobIdRoute = WorkerTaskJobIdRouteImport.update({
  id: '/task/$jobId',
  path: '/task/$jobId',
  getParentRoute: () => WorkerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/worker': typeof WorkerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/wallet': typeof ClientWalletRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wallet': typeof WorkerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/client/jobs/$jobId': typeof ClientJobsJobIdRoute
  '/client/jobs/new': typeof ClientJobsNewRoute
  '/client/review/$jobId': typeof ClientReviewJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
  '/worker/task/$jobId': typeof WorkerTaskJobIdRoute
  '/client/jobs/': typeof ClientJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/wallet': typeof ClientWalletRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wallet': typeof WorkerWalletRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/client': typeof ClientIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/client/jobs/$jobId': typeof ClientJobsJobIdRoute
  '/client/jobs/new': typeof ClientJobsNewRoute
  '/client/review/$jobId': typeof ClientReviewJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
  '/worker/task/$jobId': typeof WorkerTaskJobIdRoute
  '/client/jobs': typeof ClientJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/worker': typeof WorkerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/wallet': typeof ClientWalletRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/wallet': typeof WorkerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/client/jobs/$jobId': typeof ClientJobsJobIdRoute
  '/client/jobs/new': typeof ClientJobsNewRoute
  '/client/review/$jobId': typeof ClientReviewJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
  '/worker/task/$jobId': typeof WorkerTaskJobIdRoute
  '/client/jobs/': typeof ClientJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/worker'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/workers'
    | '/auth/admin'
    | '/auth/verify'
    | '/client/notifications'
    | '/client/wallet'
    | '/worker/profile'
    | '/worker/wallet'
    | '/admin/'
    | '/auth/'
    | '/client/'
    | '/worker/'
    | '/client/jobs/$jobId'
    | '/client/jobs/new'
    | '/client/review/$jobId'
    | '/worker/job/$jobId'
    | '/worker/task/$jobId'
    | '/client/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/workers'
    | '/auth/admin'
    | '/auth/verify'
    | '/client/notifications'
    | '/client/wallet'
    | '/worker/profile'
    | '/worker/wallet'
    | '/admin'
    | '/auth'
    | '/client'
    | '/worker'
    | '/client/jobs/$jobId'
    | '/client/jobs/new'
    | '/client/review/$jobId'
    | '/worker/job/$jobId'
    | '/worker/task/$jobId'
    | '/client/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/worker'
    | '/admin/analytics'
    | '/admin/clients'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/workers'
    | '/auth/admin'
    | '/auth/verify'
    | '/client/notifications'
    | '/client/wallet'
    | '/worker/profile'
    | '/worker/wallet'
    | '/admin/'
    | '/auth/'
    | '/client/'
    | '/worker/'
    | '/client/jobs/$jobId'
    | '/client/jobs/new'
    | '/client/review/$jobId'
    | '/worker/job/$jobId'
    | '/worker/task/$jobId'
    | '/client/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  WorkerRoute: typeof WorkerRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/wallet': {
      id: '/client/wallet'
      path: '/wallet'
      fullPath: '/client/wallet'
      preLoaderRoute: typeof ClientWalletRouteImport
      parentRoute: typeof ClientRoute
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/wallet': {
      id: '/worker/wallet'
      path: '/wallet'
      fullPath: '/worker/wallet'
      preLoaderRoute: typeof WorkerWalletRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/client/jobs/': {
      id: '/client/jobs/'
      path: '/jobs'
      fullPath: '/client/jobs/'
      preLoaderRoute: typeof ClientJobsIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/jobs/$jobId': {
      id: '/client/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/client/jobs/$jobId'
      preLoaderRoute: typeof ClientJobsJobIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/jobs/new': {
      id: '/client/jobs/new'
      path: '/jobs/new'
      fullPath: '/client/jobs/new'
      preLoaderRoute: typeof ClientJobsNewRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/review/$jobId': {
      id: '/client/review/$jobId'
      path: '/review/$jobId'
      fullPath: '/client/review/$jobId'
      preLoaderRoute: typeof ClientReviewJobIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/worker/job/$jobId': {
      id: '/worker/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/worker/job/$jobId'
      preLoaderRoute: typeof WorkerJobJobIdRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/task/$jobId': {
      id: '/worker/task/$jobId'
      path: '/task/$jobId'
      fullPath: '/worker/task/$jobId'
      preLoaderRoute: typeof WorkerTaskJobIdRouteImport
      parentRoute: typeof WorkerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWorkersRoute: AdminWorkersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientWalletRoute: typeof ClientWalletRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientJobsJobIdRoute: typeof ClientJobsJobIdRoute
  ClientJobsNewRoute: typeof ClientJobsNewRoute
  ClientReviewJobIdRoute: typeof ClientReviewJobIdRoute
  ClientJobsIndexRoute: typeof ClientJobsIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientWalletRoute: ClientWalletRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientJobsJobIdRoute: ClientJobsJobIdRoute,
  ClientJobsNewRoute: ClientJobsNewRoute,
  ClientReviewJobIdRoute: ClientReviewJobIdRoute,
  ClientJobsIndexRoute: ClientJobsIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface WorkerRouteChildren {
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerWalletRoute: typeof WorkerWalletRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
  WorkerJobJobIdRoute: typeof WorkerJobJobIdRoute
  WorkerTaskJobIdRoute: typeof WorkerTaskJobIdRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerWalletRoute: WorkerWalletRoute,
  WorkerIndexRoute: WorkerIndexRoute,
  WorkerJobJobIdRoute: WorkerJobJobIdRoute,
  WorkerTaskJobIdRoute: WorkerTaskJobIdRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  WorkerRoute: WorkerRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
